import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Shad
import { ReduxProvider } from "@/app/redux/provider";
import AppInitializer from "@/app/redux/AppInitializer";
import { TooltipProvider } from "@/components/ui/tooltip";
import SmoothScroll from "@/app/components/smoothScroll/SmoothScroll";

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <ReduxProvider>
          <AppInitializer>
            <TooltipProvider>
              <SmoothScroll>{children}</SmoothScroll>
            </TooltipProvider>
          </AppInitializer>
        </ReduxProvider>
      </body>
    </html>
  );
}
