import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/header/header";
import Footer from "@/app/components/footer/footer";

// Shad
import { Toaster } from "@/components/ui/toast";
import { ReduxProvider } from "@/app/redux/provider";
import AppInitializer from "@/app/redux/AppInitializer";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({
  subsets: ["latin", "vietnamese"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col">
        <ReduxProvider>
          <AppInitializer>
            <TooltipProvider>
              <Header />
              <main className="container mx-auto">{children}</main>
              <Toaster />
              <Footer />
            </TooltipProvider>
          </AppInitializer>
        </ReduxProvider>
      </body>
    </html>
  );
}
